In [23]:
import torch
print(torch.__version__)

2.11.0+cpu


In [24]:
if torch.cuda.is_available():
  print("GPU")
else:
  print("GPU not found! Using CPU")

GPU not found! Using CPU


Creating a Tensor


In [25]:
#using empty
#this allocates memory in space and show already put values in memory
tensor=torch.empty(2,3)

In [26]:
type(tensor)

torch.Tensor

In [27]:
zero_tensor=torch.zeros(2,3)

In [28]:
zero_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [29]:
one_torch=torch.ones(2,3)

In [30]:
one_torch

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [31]:
torch.rand(2,3)
#here values are between Zero and One Only

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [32]:
#manual_seed
torch.manual_seed(100)

In [33]:
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [34]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [35]:
torch.arange(0,10,2) #for loop types

tensor([0, 2, 4, 6, 8])

In [36]:
torch.linspace(0,10,20) # 20 evnly spaced values btween 0 to 10

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

In [37]:
torch.eye(5) # diagnol identity matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [38]:
torch.full((3,3),5) #All Values 5

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

Tensor Shape

In [39]:
x=torch.tensor([[1,2,3],[1,2,3]])
x

tensor([[1, 2, 3],
        [1, 2, 3]])

In [41]:
x.shape

torch.Size([2, 3])

In [42]:
x.reshape(1,1,6)

tensor([[[1, 2, 3, 1, 2, 3]]])

In [43]:
torch.empty_like(x)

tensor([[   208857989,            0,    111253016],
        [   536870912, 493921239040, 489626271855]])

In [44]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [45]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [46]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

Data Types

In [47]:
x.dtype

torch.int64

In [48]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32
             )

tensor([1, 2, 3], dtype=torch.int32)

In [49]:
torch.tensor([1,2,3],dtype=torch.float)

tensor([1., 2., 3.])

In [50]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [1., 2., 3.]])

Mathematical Operations

In [51]:
x=torch.rand(2,2)

In [52]:
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [53]:
x+2

tensor([[2.2627, 2.0428],
        [2.2080, 2.1180]])

In [54]:
x-2

tensor([[-1.7373, -1.9572],
        [-1.7920, -1.8820]])

In [55]:
x*3

tensor([[0.7881, 0.1285],
        [0.6241, 0.3541]])

In [56]:
x/2

tensor([[0.1313, 0.0214],
        [0.1040, 0.0590]])

In [57]:
(x *100) // 3

tensor([[8., 1.],
        [6., 3.]])

In [58]:
((x *100) // 3)%2



tensor([[0., 1.],
        [0., 1.]])

In [59]:
x**2

tensor([[0.0690, 0.0018],
        [0.0433, 0.0139]])

Element wise Operation

In [60]:
a=torch.rand(2,2)
b=torch.rand(2,2)

In [61]:
print(a,b)

tensor([[0.1217, 0.7356],
        [0.7118, 0.7876]]) tensor([[0.4183, 0.9014],
        [0.9969, 0.7565]])


In [62]:
a+b

tensor([[0.5400, 1.6370],
        [1.7087, 1.5441]])

In [63]:
a-b

tensor([[-0.2966, -0.1658],
        [-0.2851,  0.0311]])

In [64]:
a*b

tensor([[0.0509, 0.6631],
        [0.7095, 0.5958]])

In [65]:
a/b

tensor([[0.2909, 0.8160],
        [0.7140, 1.0411]])

In [66]:
a**b

tensor([[0.4143, 0.7582],
        [0.7125, 0.8347]])

In [67]:
a%b

tensor([[0.1217, 0.7356],
        [0.7118, 0.0311]])

In [72]:
torch.neg(a)

tensor([[-0.1217, -0.7356],
        [-0.7118, -0.7876]])

In [73]:
torch.abs(a)

tensor([[0.1217, 0.7356],
        [0.7118, 0.7876]])

In [75]:
torch.round(a)

tensor([[0., 1.],
        [1., 1.]])

In [76]:
torch.ceil(a)

tensor([[1., 1.],
        [1., 1.]])

In [77]:
a=torch.rand(2,2)

In [78]:
torch.floor(a)

tensor([[0., 0.],
        [0., 0.]])

In [79]:
torch.clamp(a,min=2,max=3)

tensor([[2., 2.],
        [2., 2.]])

Reduction Operation

In [87]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [81]:
e


tensor([[4, 6, 0],
        [1, 9, 9]])

In [82]:
torch.sum(e)

tensor(29)

In [84]:
torch.sum(e,axis=0)

tensor([ 5, 15,  9])

In [85]:
torch.sum(e,axis=1)

tensor([10, 19])

In [88]:
torch.mean(e)

tensor(4.)

In [89]:
torch.mean(e,dim=0)

tensor([4., 0., 8.])

In [90]:
torch.median(e)

tensor(0.)

In [92]:
torch.prod(e)

tensor(0.)

In [93]:
torch.std(e)

tensor(4.4272)

In [94]:
torch.var(e)

tensor(19.6000)

In [95]:
torch.argmax(e) #position of max number

tensor(5)

In [96]:
torch.argmin(e)

tensor(1)

MATRIX

In [97]:
f=torch.randint(size=(2,3),low=0,high=10)

In [102]:
g=torch.randint(size=(3,2),low=0,high=10)

In [100]:
torch.matmul(f,g)

tensor([[102, 135],
        [ 77, 117]])

In [105]:
a1=torch.tensor([1,2])
b1=torch.tensor([3,4])



In [106]:
torch.dot(a1,b1)

tensor(11)

In [109]:
torch.transpose(a,0,1)

tensor([[0.2239, 0.1784],
        [0.3023, 0.8238]])

In [110]:
torch.det(a)

tensor(0.1305)

In [111]:
torch.inverse(a)

tensor([[ 6.3125, -2.3167],
        [-1.3671,  1.7155]])

In [112]:
a1>b

tensor([[True, True],
        [True, True]])

In [113]:
b1>a

tensor([[True, True],
        [True, True]])

In [114]:
a1>b1

tensor([False, False])

In [115]:
a1!=b1


tensor([True, True])

Special Functions

In [124]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)

In [117]:
k

tensor([[6, 1, 5],
        [5, 0, 4]])

In [118]:
torch.log(k)

tensor([[1.7918, 0.0000, 1.6094],
        [1.6094,   -inf, 1.3863]])

In [119]:
torch.exp(k)

tensor([[403.4288,   2.7183, 148.4132],
        [148.4132,   1.0000,  54.5981]])

In [120]:
torch.sqrt(k)

tensor([[2.4495, 1.0000, 2.2361],
        [2.2361, 0.0000, 2.0000]])

In [121]:
torch.sigmoid(k)

tensor([[0.9975, 0.7311, 0.9933],
        [0.9933, 0.5000, 0.9820]])

In [125]:
torch.softmax(k,dim=0)

tensor([[0.5000, 0.9933, 0.9526],
        [0.5000, 0.0067, 0.0474]])

In [126]:
torch.relu(k)

tensor([[3., 8., 8.],
        [3., 3., 5.]])

In [127]:
m=torch.rand(2,3)

In [128]:
n=torch.rand(2,3)


In [129]:
m.add_(n)

tensor([[1.9251, 1.2663, 0.8025],
        [1.1494, 0.4199, 1.0058]])

In [130]:
m.relu_()

tensor([[1.9251, 1.2663, 0.8025],
        [1.1494, 0.4199, 1.0058]])

Copy a Tensor


In [131]:
a=torch.rand(2,3)

In [132]:
b=a.clone()

In [133]:
b


tensor([[0.3271, 0.0103, 0.9516],
        [0.2855, 0.2324, 0.9141]])

In [134]:
a

tensor([[0.3271, 0.0103, 0.9516],
        [0.2855, 0.2324, 0.9141]])

In [135]:
a[0]=0

In [136]:
a

tensor([[0.0000, 0.0000, 0.0000],
        [0.2855, 0.2324, 0.9141]])

In [137]:
b

tensor([[0.3271, 0.0103, 0.9516],
        [0.2855, 0.2324, 0.9141]])