In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
device=torch.device('cuda')

In [4]:
torch.rand((2,3),device=device)

tensor([[0.3477, 0.5953, 0.9009],
        [0.9295, 0.0031, 0.8295]], device='cuda:0')

In [5]:
a=torch.rand(2,3) #made on CPU

In [6]:
a

tensor([[0.7706, 0.0876, 0.2342],
        [0.8364, 0.2265, 0.4188]])

In [9]:
a=a.to(device) #made on GPU

In [10]:
a+5

tensor([[5.7706, 5.0876, 5.2342],
        [5.8364, 5.2265, 5.4188]], device='cuda:0')

In [11]:
import torch

In [14]:
import time

size=1000
matrix_cup1=torch.randn(size,size)
matrix_cup2=torch.randn(size,size)

start_time=time.time()
result_cpu=torch.matmul(matrix_cup1,matrix_cup2)
cpu_time=time.time()-start_time
print(cpu_time)

matrix_gup1=matrix_cup1.to('cuda')
matrix_gup2=matrix_cup2.to('cuda')
start_time=time.time()
result_gpu=torch.matmul(matrix_gup1,matrix_gup2)
torch.cuda.synchronize()
gpu_time=time.time()-start_time
print("GPU: ",gpu_time)



0.02000141143798828
GPU:  0.0010297298431396484


In [15]:
c=torch.rand(226,226,3)
c

tensor([[[0.2481, 0.0083, 0.5648],
         [0.8567, 0.9477, 0.2968],
         [0.3927, 0.1334, 0.0143],
         ...,
         [0.0082, 0.3250, 0.0116],
         [0.1604, 0.3045, 0.3412],
         [0.6622, 0.3747, 0.3530]],

        [[0.8458, 0.8449, 0.3528],
         [0.4887, 0.1294, 0.5293],
         [0.9631, 0.5668, 0.5495],
         ...,
         [0.2973, 0.5156, 0.4437],
         [0.8748, 0.0539, 0.0112],
         [0.2887, 0.4660, 0.2860]],

        [[0.3863, 0.9930, 0.2028],
         [0.3360, 0.5762, 0.3187],
         [0.5419, 0.6467, 0.1189],
         ...,
         [0.9934, 0.2866, 0.5087],
         [0.4382, 0.5986, 0.7647],
         [0.3152, 0.3755, 0.8379]],

        ...,

        [[0.2804, 0.7811, 0.8440],
         [0.4811, 0.1821, 0.1449],
         [0.5646, 0.8286, 0.6883],
         ...,
         [0.4259, 0.7762, 0.4377],
         [0.9243, 0.0494, 0.4951],
         [0.3797, 0.7070, 0.0089]],

        [[0.6507, 0.2150, 0.0114],
         [0.6329, 0.7513, 0.8425],
         [0.

In [16]:
c.unsqueeze(0,).shape #position where you want to add dim

torch.Size([1, 226, 226, 3])

In [17]:
c.squeeze(0,).shape

torch.Size([226, 226, 3])

In [18]:
import numpy as np


In [19]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [20]:
b=a.numpy()

In [21]:
b

array([1, 2, 3])

In [22]:
type(b)

numpy.ndarray

In [23]:
c=np.array([1,2,3])

In [24]:
c

array([1, 2, 3])

In [25]:
torch.from_numpy(c)

tensor([1, 2, 3])